## <center> Analyzing Flight Delays and Cancellations <center>

In [1]:
# Import necessary libraries
import pandas as pd  
import numpy as np 
import matplotlib.pyplot as plt

In [ ]:
# Import flights dataset
flights = pd.read_csv("C:/Users/uyen/Desktop/Real-World-Projects/Python/datasets/flights2022.csv")
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,555,N405UA,SEA,IAH,221.0,1874,23,59,2022-01-01T23:00:00Z,United Air Lines Inc.
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,72,N265AK,SEA,FAI,193.0,1533,22,50,2022-01-01T22:00:00Z,Alaska Airlines Inc.
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,270,N274AK,SEA,ATL,261.0,2182,23,55,2022-01-01T23:00:00Z,Alaska Airlines Inc.
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,7,N281AK,SEA,ORD,193.0,1721,23,50,2022-01-01T23:00:00Z,Alaska Airlines Inc.
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,507,N426UA,PDX,ORD,196.0,1739,23,49,2022-01-01T23:00:00Z,United Air Lines Inc.

In [3]:
# Import weather dataset
weather = pd.read_csv("C:/Users/uyen/Desktop/Real-World-Projects/Python/datasets/flights_weather2022.csv")
weather.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,route,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,...,SEA-IAH,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,...,SEA-FAI,32.0,23.0,69.04,170.0,9.20624,10.594357,0.0,1023.4,10.0
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,...,SEA-ATL,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,...,SEA-ORD,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,...,PDX-ORD,33.0,19.0,55.75,120.0,6.90468,7.945768,0.0,1025.1,10.0

In [8]:
# Create the route column in the flights dataset
flights["route"] = flights["origin"] + '-' + flights["dest"]
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline,route
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,...,N405UA,SEA,IAH,221.0,1874,23,59,2022-01-01T23:00:00Z,United Air Lines Inc.,SEA-IAH
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,...,N265AK,SEA,FAI,193.0,1533,22,50,2022-01-01T22:00:00Z,Alaska Airlines Inc.,SEA-FAI
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,...,N274AK,SEA,ATL,261.0,2182,23,55,2022-01-01T23:00:00Z,Alaska Airlines Inc.,SEA-ATL
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,...,N281AK,SEA,ORD,193.0,1721,23,50,2022-01-01T23:00:00Z,Alaska Airlines Inc.,SEA-ORD
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,...,N426UA,PDX,ORD,196.0,1739,23,49,2022-01-01T23:00:00Z,United Air Lines Inc.,PDX-ORD

In [10]:
# Observe the unique routes for flights
unique_flights = flights["route"].unique()

In [17]:
# Observe the unique origin airports
flights["origin"].unique()

array(['SEA', 'PDX'], dtype=object)

In [23]:
# Observe the unique dest airports
flights["dest"].unique()

array(['IAH', 'FAI', 'ATL', 'ORD', 'JFK', 'MIA', 'PSC', 'IAD', 'DEN',
       'PHX', 'MDW', 'OAK', 'DFW', 'LAS', 'SLC', 'PDX', 'SJC', 'CLT',
       'SNA', 'DTW', 'LAX', 'SEA', 'SAN', 'SFO', 'MSP', 'ONT', 'ANC',
       'PSP', 'HNL', 'ICT', 'MSO', 'KOA', 'STS', 'BOS', 'BOI', 'CMH',
       'OKC', 'SBA', 'SMF', 'DAL', 'TUS', 'PHL', 'GEG', 'FLL', 'AUS',
       'OGG', 'LIH', 'BZN', 'RDU', 'RSW', 'STL', 'DCA', 'MRY', 'MCO',
       'EWR', 'MFR', 'BLI', 'FAT', 'RDM', 'EUG', 'TPA', 'BIL', 'ABQ',
       'IND', 'FCA', 'CVG', 'BUR', 'MCI', 'PIT', 'OMA', 'PUW', 'MSY',
       'JAC', 'MKE', 'RNO', 'ALW', 'HLN', 'BNA', 'SAT', 'EAT', 'HDN',
       'JNU', 'YKM', 'GTF', 'ELP', 'SUN', 'KTN', 'SBP', 'RDD', 'IDA',
       'BWI', 'CHS', 'PAE', 'GRR', 'DSM', 'SIT', 'CLE'], dtype=object)

In [16]:
# Calculate the average departure delays in minutes for routes
avg_delay_routes = pd.DataFrame(flights.groupby(["route"])["dep_delay"].mean()).reset_index()
avg_delay_routes

       route  dep_delay
0    PDX-ABQ   1.098039
1    PDX-ANC   4.748936
2    PDX-ATL   7.020979
3    PDX-AUS   5.435374
4    PDX-BOI   5.136430
..       ...        ...
144  SEA-STS   6.782493
145  SEA-SUN   5.735537
146  SEA-TPA   6.537344
147  SEA-TUS   6.161290
148  SEA-YKM   5.427350

[149 rows x 2 columns]

In [ ]:
# Observe the cancelled flights
flights[flights["dep_time"].isna()]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline,route
485,2022,1,1,NaN,1845,NaN,NaN,2104,NaN,OO,...,N182SY,PDX,PSP,NaN,873,18,45,2022-01-01T18:00:00Z,SkyWest Airlines Inc.,PDX-PSP
486,2022,1,1,NaN,945,NaN,NaN,1135,NaN,OO,...,N178SY,PDX,SJC,NaN,569,9,45,2022-01-01T09:00:00Z,SkyWest Airlines Inc.,PDX-SJC
487,2022,1,1,NaN,1327,NaN,NaN,1905,NaN,OO,...,N277SY,SEA,MCI,NaN,1489,13,27,2022-01-01T13:00:00Z,SkyWest Airlines Inc.,SEA-MCI
488,2022,1,1,NaN,1715,NaN,NaN,1925,NaN,OO,...,N253SY,PDX,LAX,NaN,834,17,15,2022-01-01T17:00:00Z,SkyWest Airlines Inc.,PDX-LAX
489,2022,1,1,NaN,1515,NaN,NaN,1620,NaN,OO,...,N272SY,SEA,RDM,NaN,228,15,15,2022-01-01T15:00:00Z,SkyWest Airlines Inc.,SEA-RDM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111371,2022,6,30,NaN,1155,NaN,NaN,2033,NaN,UA,...,NaN,SEA,EWR,NaN,2402,11,55,2022-06-30T11:00:00Z,United Air Lines Inc.,SEA-EWR
111372,2022,6,30,NaN,1448,NaN,NaN,1732,NaN,DL,...,N3759,SEA,LAX,NaN,954,14,48,2022-06-30T14:00:00Z,Delta Air Lines Inc.,SEA-LAX
111373,2022,6,30,NaN,1751,NaN,NaN,2352,NaN,DL,...,N898DN,SEA,ORD,NaN,1721,17,51,2022-06-30T17:00:00Z,Delta Air Lines Inc.,SEA-ORD
111374,2022,6,30,NaN,1145,NaN,NaN,2029,NaN,DL,...,N876DN,SEA,JFK,NaN,2422,11,45,2022-06-30T11:00:00Z,Delta Air Lines Inc.,SEA-JFK
111375,2022,6,30,NaN,720,NaN,NaN,1544,NaN,DL,...,N814DN,SEA,BOS,NaN,2496,7,20,2022-06-30T07:00:00Z,Delta Air Lines Inc.,SEA-BOS